[workspace]

members = [
    "lightning",
    "lightning-net-tokio",
]

# Our tests do actual crypo and lots of work, the tradeoff for -O1 is well worth it
[profile.test]
opt-level = 1

[profile.dev]
panic = "abort"

[profile.release]
opt-level = 3
lto = true
panic = "abort"
