[package]
name = "lightning-persister"
version = "0.0.1"
authors = ["Valentine Wallace", "Matt Corallo"]
license = "Apache-2.0"
description = """
Utilities to manage channel data persistence and retrieval.
"""

[dependencies]
bitcoin = "0.24"
lightning = { version = "0.0.12", path = "../lightning" }
libc = "0.2"

[dev-dependencies.bitcoin]
version = "0.24"
features = ["bitcoinconsensus"]

[dev-dependencies]
lightning = { version = "0.0.12", path = "../lightning", features = ["_test_utils"] }
