[package]
name = "lightning-persister"
version = "0.0.13"
authors = ["Valentine Wallace", "Matt Corallo"]
license = "Apache-2.0"
description = """
Utilities to manage channel data persistence and retrieval.
"""

[dependencies]
bitcoin = "0.26"
lightning = { version = "0.0.13", path = "../lightning" }
libc = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winbase"] }

[dev-dependencies.bitcoin]
version = "0.26"
features = ["bitcoinconsensus"]

[dev-dependencies]
lightning = { version = "0.0.13", path = "../lightning", features = ["_test_utils"] }
