[package]
name = "lightning-background-processor"
version = "0.0.99"
authors = ["Valentine Wallace <vwallace@protonmail.com>"]
license = "MIT OR Apache-2.0"
repository = "http://github.com/rust-bitcoin/rust-lightning"
description = """
Utilities to perform required background tasks for Rust Lightning.
"""
edition = "2018"

[dependencies]
bitcoin = "0.27"
lightning = { version = "0.0.99", path = "../lightning", features = ["allow_wallclock_use"] }
lightning-persister = { version = "0.0.99", path = "../lightning-persister" }

[dev-dependencies]
lightning = { version = "0.0.99", path = "../lightning", features = ["_test_utils"] }

